### ISSUE TITLE
SFSafariViewController links error

### ISSUE THREAD

**Issue by kshahim0** [Larpon/QtFirebase#54]
thanks for this wonderful project, after following the setup guidelines, I receive these errors:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SFSafariViewController", referenced from:
      objc-class-ref in FirebaseAuth(FIRAuthURLPresenter_f9c1670c7b472e1f12d82d1c6f46940a.o)
  "_OBJC_CLASS_$_FIRLifecycleEvents", referenced from:
      objc-class-ref in FirebaseRemoteConfig(RCNConfigExperiment_8bc114fd2122a8a3d08208ec2bfe88e0.o)
  "_OBJC_CLASS_$_FIRExperimentController", referenced from:
      objc-class-ref in FirebaseRemoteConfig(RCNConfigExperiment_8bc114fd2122a8a3d08208ec2bfe88e0.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

it seems, SFSafariViewController is not found, is it due to the SDK or new policy on webiew?
any hint is appreciated...

**Comment by Larpon** [comment]
Hey @kshahim0 - thanks for trying the project out!

Uhm - I have never seen that error before. What version of the Firebase C++ SDK are you using?
We haven't tested builds against 4.2.0 yet - everything should work with 4.1.0 though.

On first glimpse it look like it could be a problem outside QtFirebase. I'll try and build the example app against 4.2.0 and the latest iOS SDK and see if I get the same error

**Comment by Larpon** [comment]
@kshahim0 - I found the error. It should be fixed in commit 954be10

The commit works with
Firebase C++ SDK v4.2.0
Firebase iOS SDK v4.4.0, v4.5.0 and v4.6.0

The problem was a 1 documented and 1 undocumented missing framework inclusion:
* FirebaseAuth now requires the SafariServices framework
* FirebaseRemoteConfig now also need the FirebaseABTesting framework

Hope you can get it to work now.

**Comment by kshahim0** [comment]
Thanks Larpon, now it is compiled successfully!

**Comment by kshahim0** [comment]
Thanks Larpon, now it is compiled and running successfully 

are there also support for Google or Facebook sign in?

thanks for this great project!

**Comment by Larpon** [comment]
@kshahim0 - good to hear :)

Nope the `Auth` module is still partial - and only have functionality for email based user sign-in
**But** I happen to know that @isipisi281 is supposedly working on some of it - what, where and when is unknown though

**Comment by kshahim0** [comment]
Ok, thanks Larpon,

since two weeks i am working on this aspect to use full functionality of firebase auth, not yet succeeded 

if you want I can participate on the Google, Facebook  sign in, for the authentication part, I have time for it
as i need them for my application :)

if yes, i need your guidance to give me direction for the implementation.

Let me know,
Best,
Kamal

**Comment by Larpon** [comment]
That sounds awesome @kshahim0 - we can always use more hands :)

I'm not in-depth with the Auth contributions but I do know the implementations will require some native coding (e.g. Java and Objective-C) - I suggest you try to ask @isipisi281 and see how far he is? I'll be happy to help out with any questions regarding the QtFirebase project in general. I'm thinking you could split the burden between you - one takes Google and one takes Facebook?

We haven't got any official guidelines for code style yet, but we follow Qt's coding style as much as possible. You can try and read through one of the modules to see how it all looks.

But basically a "full" contribution would include:
* A working QML & C++ implementation for both Android and iOS on the given login provider
* A [stub implementation](https://github.com/Larpon/QtFirebase/tree/master/fake/src) for unsupported platforms

We currently hangout on Slack (https://qtmob.slack.com)

I think this still works: http://org-qtmob-slackin.herokuapp.com/

**Comment by kshahim0** [comment]
Hi Larpon, 

perfect, I have started reading the codes for firebase example and exploring them further in details.

I have joined also the Slack section.

I am going to ask isipisi281 right now to know how far is the development part, so we can split it to different parts.

I will keep you informed,
Best,
Kamal
