### ISSUE TITLE
Latest Changes broke Qt 5.9.6 compatibility

### ISSUE THREAD

**Issue by GaRaOne** [Larpon/QtFirebase#84]
works with 5.11.1
failed with 5.9.6

http://doc.qt.io/qt-5/qmetaobject.html#invokeMethod-4
"This function was introduced in Qt 5.10."

`../../sdk/qt-firebase/src/qtfirebaseadmob.cpp: In lambda function:
../../sdk/qt-firebase/src/qtfirebaseadmob.cpp:557:18: error: no matching function for call to 'QMetaObject::invokeMethod(QtFirebaseAdMobBase*, QtFirebaseAdMobBase::init()::<lambda(const firebase::FutureBase&)>::<lambda()>)'
                 });
                  ^
../../sdk/qt-firebase/src/qtfirebaseadmob.cpp:557:18: note: candidates are:
In file included from ../../../../sdk/qt/5.9.6/android_armv7/include/QtCore/qobject.h:46:0,
                 from ../../../../sdk/qt/5.9.6/android_armv7/include/QtCore/qiodevice.h:45,
                 from ../../../../sdk/qt/5.9.6/android_armv7/include/QtCore/qtextstream.h:43,
                 from ../../../../sdk/qt/5.9.6/android_armv7/include/QtCore/qdebug.h:49,
                 from ../../../../sdk/qt/5.9.6/android_armv7/include/QtCore/QDebug:1,
                 from ../../sdk/qt-firebase/src/platformutils.h:4,
                 from ../../sdk/qt-firebase/src/qtfirebase.h:9,
                 from ../../sdk/qt-firebase/src/qtfirebaseadmob.h:6,
                 from ../../sdk/qt-firebase/src/qtfirebaseadmob.cpp:1:
../../../../sdk/qt/5.9.6/android_armv7/include/QtCore/qobjectdefs.h:406:17: note: static bool QMetaObject::invokeMethod(QObject*, const char*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
     static bool invokeMethod(QObject *obj, const char *member,
                 ^
../../../../sdk/qt/5.9.6/android_armv7/include/QtCore/qobjectdefs.h:406:17: note:   candidate expects 14 arguments, 2 provided
../../../../sdk/qt/5.9.6/android_armv7/include/QtCore/qobjectdefs.h:420:24: note: static bool QMetaObject::invokeMethod(QObject*, const char*, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
     static inline bool invokeMethod(QObject *obj, const char *member,
                        ^
../../../../sdk/qt/5.9.6/android_armv7/include/QtCore/qobjectdefs.h:420:24: note:   candidate expects 13 arguments, 2 provided
../../../../sdk/qt/5.9.6/android_armv7/include/QtCore/qobjectdefs.h:437:24: note: static bool QMetaObject::invokeMethod(QObject*, const char*, Qt::ConnectionType, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
     static inline bool invokeMethod(QObject *obj, const char *member,
                        ^
../../../../sdk/qt/5.9.6/android_armv7/include/QtCore/qobjectdefs.h:437:24: note:   candidate expects 13 arguments, 2 provided
../../../../sdk/qt/5.9.6/android_armv7/include/QtCore/qobjectdefs.h:454:24: note: static bool QMetaObject::invokeMethod(QObject*, const char*, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
     static inline bool invokeMethod(QObject *obj, const char *member,
                        ^
../../../../sdk/qt/5.9.6/android_armv7/include/QtCore/qobjectdefs.h:454:24: note:   no known conversion for argument 2 from 'QtFirebaseAdMobBase::init()::<lambda(const firebase::FutureBase&)>::<lambda()>' to 'const char*'`

**Comment by Larpon** [comment]
Thanks for the report. Looking in to it

**Comment by Larpon** [comment]
@GaRaOne - should be fixed in 8a01bc1 - feel free to re-open if the problem continues!
